const prefix = [
  'You have successfully completed “',
  'Congratulations Art Traveler! You have successfully completed Suarteroad',
  'Success! Your order for ',
  'Exciting news! ',
  'You have confirmed the reception of ',
  'Just checking. Have you received ',
  '',
  'Success! Your Limited Edition order of ',
  'Your Limited Edition of ',
  'You have successfully confirmed the reception of your new Limited Edition',
  'Just checking. Have you received the Limited Edition ',
  'You have successfully completed “',
  'Congratulations Art Traveler! You have successfully completed Suarteroad',
  'Success! Your Limited Edition order of has been placed! ',
  'Exciting news! ',
  'You have confirmed the reception of ',
  'Just checking. Have you received ',
  '',
  'Success! Your Limited Edition order of ',
  'Your Limited Edition of ',
  'You have successfully confirmed the reception of your new Limited Edition',
  'Just checking. Have you received the Limited Edition ',
  '',
  'The request for Limited Editions on ',
  'Great news! The Limited Editions of ',
  'Submission approved! ',
  'Submission approved! ',
  'Changes required. Please make the necessary updates for ',
  'Limited Edition request for ',
  'Changes are required for the Limited Edition request of ',
  'Congratulations! ',
  'Congratulations! ',
  '6 days left to ship [Artwork Title] by [Artist Name]. Please prepare the artwork for shipment and introduce the the shipping information in the orders tab.',
  'Important reminder: You have 3 days left to ship ',
  'Take action! You have 24 hours left to ship ',
  'Shipping information added! ',
  'Order completed! The artwork ',
  ' A new review for ',
  '',
  'Limited Edition [N of L.E(e.g. 1/100)] of ',
  'What an achievement! Limited Editions of ',
  'Congratulations! You have completed the sale of ',
  ''
];

const midfix = [
  ' ',
  ' ',
  ' by ',
  ' by ',
  ' by ',
  ' by ',
  ' ',
  ' by ',
  ' by ',
  ' ',
  ' by ',
  ' ',
  ' ',
  ' by ',
  ' by ',
  ' by ',
  ' by ',
  ' ',
  ' by ',
  ' by ',
  ' ',
  ' by ',
  ' uploaded ',
  ' ',
  ' ',
  ' by ',
  ' by ',
  ' by ',
  ' by ',
  ' by ',
  ' by ',
  ' by ',
  ' ',
  ' by ',
  ' by ',
  ' ',
  ' ',
  ' by ',
  ' ',
  ' by ',
  ' by ',
  ' by ',
  ' by '
];

const suffix = [
  '”! Go to Suarteroad to see what’s next',
  '',
  ' has been placed! We will keep you updated on its progress',
  ' is on its way. Get ready to welcome it home',
  '. Enjoy your unique piece!',
  '? If so, please confirm its reception',
  ' sent you a new message',
  ' has been placed!',
  ' is on its way. Prepare to give it a warm welcome!',
  '',
  '? If so, please confirm its reception',
  '”! Go to Suarteroad to see what’s next',
  '',
  ' has been placed! We will keep you updated on its progress',
  ' is on its way. Get ready to welcome it home',
  '. Enjoy your unique piece!',
  '? If so, please confirm its reception',
  ' sent you a new message',
  ' has been placed!',
  ' is on its way. Prepare to give it a warm welcome!',
  '',
  '? If so, please confirm its reception',
  ' together with Limited Editions and are now available for purchase',
  ', has been accepted',
  ' have sold out!',
  ' is now available for purchase',
  ' and its Limited Edition are now available for purchase',
  '',
  ' has been approved!',
  '',
  ' has been purchased!',
  ' has been purchased!  The collector has added a message',
  '. Please prepare the artwork for shipment and introduce the the shipping information in the orders tab.',
  '. Click here to Introduce shipping details.',
  '. Click here to Introduce shipping details.',
  ' is on its way to the collector.',
  ' has been received.',
  ' has been added: ',
  ' sent you a new message regarding ',
  ' has been sold! ',
  ' are SOLD OUT!',
  ' in your gallery.',
  ' has been claimed on Suarte by '
];

export { prefix, midfix, suffix };