const artLover = [
  {
    type: true,
    status: 0,
    subject: "Complete your profile",
    sbj_image: "./assets/svg/user.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Like 10 artworks",
    sbj_image: "./assets/svg/like.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Follow 5 users",
    sbj_image: "./assets/svg/like.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Write 3 thoughts",
    sbj_image: "./assets/svg/thought.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Create an artlist",
    sbj_image: "./assets/svg/artlist.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Rate 5 artworks",
    sbj_image: "./assets/svg/rate.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Play an audio",
    sbj_image: "./assets/svg/play.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Start your collection",
    sbj_image: "./assets/svg/collection.svg",
  },
  {
    type: true,
    status: 1,
    sbj_image: "./assets/svg/roadcomp.svg",
  },
  {
    type: true,
    status: 2,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 3,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 4,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 5,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 6,
    subject: "Zanyu Fine Art",
    sbj_image: "./assets/svg/message.svg",
  },
  {
    type: true,
    status: 7,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 8,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 9,
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 10,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/order.svg",
    obj_image: "./objimg.png",
  },
];

const artist = [
  {
    type: true,
    status: 0,
    subject: "Complete your profile",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Like 10 artworks",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Follow 5 users",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Write 3 thoughts",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Create an artlist",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Rate 5 artworks",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Play an audio",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 0,
    subject: "Get 3 artworks represented at Suarte",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 1,
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 2,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 3,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 4,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    stauts: 5,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 6,
    subject: "Zanyu Fine Art",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 7,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 8,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 9,
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 10,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 23,
    subject: "City",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 24,
    subject: "City",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
];

const gallery = [
  {
    type: true,
    status: 25,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 26,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 27,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 28,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 29,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 30,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 31,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 32,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 33,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 34,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 35,
    subject: "Testudo Graeca",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 36,
    subject: "Testudo Graeca",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 37,
    subject: "Port Scene",
    object: "Francisco Carmena",
    result: "I'm very happy with y new acquistion. Everything has been perfect!",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 37,
    subject: "Heritage",
    object: "Francisco Carmena",
    result: "I'm not disappointed but I expected way different colors.",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 37,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    result: "It has been a disaster!",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 38,
    subject: "marina",
    result: "Testudo Graeca",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 40,
    subject: "Albufera",
    object: "Jose Hernandez",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 39,
    subject: "Albufera",
    object: "Jose Hernandez",
    sbj_image: "./assets/svg/.svg",
  },
  {
    type: true,
    status: 42,
    subject: "Mechanical Marines Jaw Line",
    object: "Lingee Bangkhuntod",
    result: "marina",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 41,
    subject: "Mechanical Marines Jaw Line",
    object: "Lingee Bangkhuntod",
    sbj_image: "./assets/svg/.svg",
    obj_image: "./objimg.png",
  }
];

const interaction = [
  {
    type: false,
    status: 0,
    subject: "marina",
    object: "Mechanical Morines Jaw Lines",
    result: ": I bet he has a heart of steel",
    period: " 15s",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/chHoJhvXrac6qyYYZpuJnK4pTCH2_64b4f45223a3c4bff85baf6d/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 1,
    subject: "marina",
    object: "Testudo Graeca",
    result: ": It does, right?",
    period: " 1h",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/chHoJhvXrac6qyYYZpuJnK4pTCH2_64b4f45223a3c4bff85baf6d/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 2,
    subject: "marina",
    object: "Testudo Graeca",
    result: ": He looks kinda fast",
    period: " 15s",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/chHoJhvXrac6qyYYZpuJnK4pTCH2_64b4f45223a3c4bff85baf6d/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 3,
    subject: "theartrefugee",
    object: "Heritage",
    result: ": I ALSO LOVE MARIO😍😍😍",
    period: " 1h",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/C3ACgHqpeNV3nDl5sddTFfNe1yJ3_649c2be846219a56254be0d8/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 4,
    subject: "javi",
    object: "Mechanical Marines Jaw Lines",
    period: " 2h",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/Og9ScQAkBdcPfZmoNjvqdI0n6EA2_649c093e49ffe97bb06d45b5/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 6,
    subject: "javi",
    object: "Mechanical Marines Jaw Lines",
    period: " 2h",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/Og9ScQAkBdcPfZmoNjvqdI0n6EA2_649c093e49ffe97bb06d45b5/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 5,
    subject: "",
    object: "",
    result: ": ",
    period: " ",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/chHoJhvXrac6qyYYZpuJnK4pTCH2_64b4f45223a3c4bff85baf6d/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 7,
    subject: "marina",
    period: " 15s",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/chHoJhvXrac6qyYYZpuJnK4pTCH2_64b4f45223a3c4bff85baf6d/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 7,
    subject: "artist_username",
    period: " 15s",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/fvpVOJsW0VY2ozHF8HbtdDqifOg2_649dfabe12a93a8802e159f2/w=200",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 7,
    subject: "gallery_username",
    period: " 15s",
    sbj_image: "https://suarte.art/cdn-cgi/imagedelivery/hAeIC__6Aj746x0RFU1joA/M5LS4dtKQEYOGjzE155DikrMm8g1_649c24d146219a56254bb09e/w=200",
    obj_image: "./objimg.png",
  },
];

export { artLover, artist, gallery, interaction };