const artLover = [
  {
    type: true,
    status: 0,
    subject: "Complete your profile",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Like 10 artworks",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Follow 5 users",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Write 3 thoughts",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Create an artlist",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Rate 5 artworks",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Play an audio",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Start your collection",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 1,
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 2,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 3,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 4,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 5,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 6,
    subject: "Zanyu Fine Art",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 7,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 8,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 9,
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 10,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
];

const artist = [
  {
    type: true,
    status: 0,
    subject: "Complete your profile",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Like 10 artworks",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Follow 5 users",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Write 3 thoughts",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Create an artlist",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Rate 5 artworks",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Play an audio",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 0,
    subject: "Get 3 artworks represented at Suarte",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 1,
    sbj_image: "./subimg.png",
  },
  {
    type: false,
    status: 2,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 3,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: false,
    status: 4,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    stauts: 5,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 6,
    subject: "Zanyu Fine Art",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 7,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 8,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 9,
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 10,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 23,
    subject: "City",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 24,
    subject: "City",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
];

const gallery = [
  {
    type: true,
    status: 25,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 26,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 27,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 28,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 29,
    subject: 'City',
    object: 'Saeid Mojavari',
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 30,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 31,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 32,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 33,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 34,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 35,
    subject: "Testudo Graeca",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 36,
    subject: "Testudo Graeca",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 37,
    subject: "Port Scene",
    object: "Francisco Carmena",
    result: "I'm very happy with y new acquistion. Everything has been perfect!",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 37,
    subject: "Heritage",
    object: "Francisco Carmena",
    result: "I'm not disappointed but I expected way different colors.",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 37,
    subject: "Testudo Graeca",
    object: "Francisco Carmena",
    result: "It has been a disaster!",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 38,
    subject: "marina",
    result: "Testudo Graeca",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 40,
    subject: "Albufera",
    object: "Jose Hernandez",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 39,
    subject: "Albufera",
    object: "Jose Hernandez",
    sbj_image: "./subimg.png",
  },
  {
    type: true,
    status: 42,
    subject: "Mechanical Marines Jaw Line",
    object: "Lingee Bangkhuntod",
    result: "marina",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  },
  {
    type: true,
    status: 41,
    subject: "Mechanical Marines Jaw Line",
    object: "Lingee Bangkhuntod",
    sbj_image: "./subimg.png",
    obj_image: "./objimg.png",
  }
];

export { artLover, artist, gallery };